spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true #内部默认已开启，这里列出来说明这个参数比较重要
  application:
    name: zuul-server
server:
  port: 5555
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true
zuul:
  retryable: true #开启重试，D版之后默认为false，需要手动开启
  ribbon:
    eager-load:
      enabled: false #开启饥饿加载
  routes:
    client-a:
      path: /client/**
      serviceId: client-a
#禁用HttpClient并开启OkHttp
ribbon:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
#重试机制配置
  ConnectTimeout: 3000 #请求连接的超时时间   # http客户端为httpclient才生效 默认5秒
  ReadTimeout: 3000 #请求处理的超时时间      # http客户端为httpclient才生效 默认5秒
  MaxAutoRetries: 1 # 同一服务器上的最大重试次数（不包括第一次尝试）         推荐设置为0
  MaxAutoRetriesNextServer: 1 #下一个要重试的服务器的最大数量（不包括第一个服务器） 推荐设置为0
  OkToRetryOnAllOperations: true # 确定重试 推荐设置为fasle