server:
  port: 7777
spring:
  application:
    name: ch62-eureka-client-provider
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true