server:
  port: 9088
spring:
  application:
    name: turbine-dashboard
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
turbine:
  appConfig: ch623-eureka-client-consumer,ch623-eureka-client-provider
  clusterNameExpression: "'default'"