server:
  port: 7071
spring:
  profiles: node1
  application:
    name: client-a
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      host-mark: running-host