server:
  port: 9090
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/keepclimbs/springcloud-config-server.git # git容器地址
          search-paths: config-folder    # git容器中的文件夹
  application:
    name: config-server
