server:
  port: 9090
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/keepclimbs/springcloud-config-server.git
          search-paths: config-folder
  application:
    name: config-server
