spring:
  application:
    name: zuul-server
  servlet:  #spring boot2.0之前是http
    multipart:
      enabled: true   # 使用http multipart上传处理
      max-file-size: 1MB # 设置单个文件的最大长度，默认1M，如不限制配置为-1
      max-request-size: 1MB # 设置最大的请求文件的大小，默认10M，如不限制配置为-1
      file-size-threshold: 1MB  # 当上传文件达到1MB的时候进行磁盘写入
      location: /  # 上传的临时目录 （在当前项目目录下）
server:
  port: 5555
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true
