spring:
  application:
    name: zuul-server
server:
  port: 5555
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: '*' # 加载所有的端点/默认只加载了 info / health
  endpoint:
    health:
      show-details: always # 展示详细信息
zuul:
  ignored-patterns: /**/div/**
  routes:
    client-a:
      path: /client/**
      serviceId: client-a
#      跳过前缀, 为true跳过前缀， 没有测试过
#      stripPrefix: false
  ribbon:
    eager-load:
      enabled: true
