server:
  port: 9091
spring:
  application:
    name: ch623-eureka-client-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
feign:
  hystrix:
    enabled: true
ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: ch623-eureka-client-provider

ch623-eureka-client-provider:
  ribbon:
    ConnectTimeout: 6000 #请求连接的超时时间
    ReadTimeout: 6000 #请求处理的超时时间
    MaxAutoRetries: 1 # 同一服务器上的最大重试次数（不包括第一次尝试）
    MaxAutoRetriesNextServer: 1 #下一个要重试的服务器的最大数量（不包括第一个服务器）
hystrix:
  command:
    default:
      execution:
        timeout:
        isolation:
          thread:
            timeoutInMilliseconds: 15000