server:
  port: 8022
spring:
  application:
    name: ch512-eureka-client

eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
